### ISSUE TITLE
iOS?

### ISSUE THREAD

**Issue by ghost** [DG0BAB/Apocha#1]
I was interested in giving this a try in our iOS app, since your description seems to indicate that it will work. I discovered that iOS's Security framework doesn't have the SecAsn1Coder (along with a lot of other stuff in OSX's Security framework). Is that something you've got planned or have been working on (I'm guessing it would require openssl)?

**Comment by DG0BAB** [comment]
Thanks for getting in contact. Sadly Apocha isn't ready for primetime so far. It should work on macOS but there's still a lot to do on the iOS side. Since I'm doing it all in spare time I can't say when it's done. I'm currently looking for a replacement of OpenSSL since Apple discourage using it. I may have found an alternative with WolfSSL. It's free, fast, small and open source. Have a [look](https://www.wolfssl.com/wolfSSL/Home.html) at it.
